version: '3'

networks: 
  dockersql-network:
    driver: bridge
    
services:
  webApp.MVC:
    container_name: webApp.MVC
    image: question-store-mvc
    build:
      context: .
      dockerfile: Src/QuestionStore.WebApp.MVC/Dockerfile  
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "5055:80"
    networks:
      - dockersql-network
    depends_on:
      - db.database
  webApp.API:
    container_name: webApp.API
    image: question-store-api
    build:
      context: .
      dockerfile: Src/QuestionStore.WebApp.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - dockersql-network
    depends_on:
      - db.database
  db.database:
    container_name: mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
  fb.database:
    container_name: firebird
    image: jacobalberty/firebird:3.0.4
    ports:
      - "3050:3050"
    environment:
      - ISC_PASSWORD=masterkey
      
    