version: '3'

networks: 
  dockersql-network:
    driver: bridge
    
services:
  db.database.prod:
    image: mysql:5.6
    ports:
      - "3305:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development

      

